name: Run basic e2e tests

on:
  pull_request:

jobs:
  check:
    name: Run e2e tests for basic scenarios
    uses: ./.github/workflows/subflow_run_e2e_tests.yaml
    with:
      e2e_filter: "basic"
